apiVersion: api-management.sensedia.com/v1
kind: Environment
spec:
  name: CLI - Prd
  description: CLI prd environment
  deploymentPermission:
    type: Organization
  tracePermission:
    type: Organization
  gatewayPoolRef:
    name: default
  inboundURL:
    inboundAddressRef:
      name: CLI - Prd
    path: ""
  mapVars:
    - description: Description for API Sample
      name: Map sample
      vars:
        - key: url-cli-sample
          value: https://swapi.dev/apis
          variableType: DEFAULT
