name: CI/CD

on:
  push:
    branches:
      - main
      - hml
      - dev
jobs:
  build:
    name: Build Stage
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: |
          sudo apt-get update && sudo apt-get install -y wget curl yamllint &&
          curl -L https://cli.sensedia.com/2.8.0/ssd-linux-amd64/ssd -o ssd &&
          chmod +x ssd && mv ssd /usr/local/bin
      - name: filter differences
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > .diff-files
          cat .diff-files | grep -v ".github/" | grep .yaml  > .crds-to-apply | true
      - name: test/lint
        run: yamllint .
      - name: Configure CLI environment
        run: |
          ssd configure --url ${{ secrets.SENSEDIA_CLI_MANAGER_URL }} --token ${{ secrets.SENSEDIA_CLI_TOKEN  }} -o json
      - name: build artifact
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: .
  deploy_main:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy prod
    environment: main
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: .

      - name: Apply changed files
        run: |
          echo "all newed/changed CRDs"
          cat .crds-to-apply

          echo "ssd apply -f in all kind RestAPI"
          cat .crds-to-apply | grep "restapi-" > .crds-restapi-to-apply | true
          cat .crds-restapi-to-apply | xargs -n 1 --no-run-if-empty -t ./ssd apply -f

          echo "ssd apply -f in all kind Environment"
          cat .crds-to-apply | grep "env-" > .crds-env-to-apply | true
          cat .crds-env-to-apply | xargs -n 1 --no-run-if-empty -t ./ssd apply -f

          echo "ssd apply -f in all kind ApiEnvironmentLink"
          cat .crds-to-apply | grep "apienvlink-" > .crds-appenvlink-to-apply | true
          cat .crds-appenvlink-to-apply | xargs -n 1 --no-run-if-empty -t ./ssd apply -f

          echo "ssd apply -f in all kind Deployment"
          cat .crds-to-apply | grep "deployment-" > .crds-deployment-to-apply | true
          cat .crds-deployment-to-apply | xargs -n 1 --no-run-if-empty -t ./ssd apply -f

          echo "ssd apply -f in all kind Plan"
          cat .crds-to-apply | grep "plan-" > .crds-plan-to-apply | true
          cat .crds-plan-to-apply | xargs -n 1 --no-run-if-empty -t ./ssd apply -f

          echo "ssd apply -f in all kind App"
          cat .crds-to-apply | grep "app-" > .crds-app-to-apply | true
          cat .crds-app-to-apply | xargs -n 1 --no-run-if-empty -t ./ssd apply -f
